services:
  wildfly:
    build: .
    ports:
      - "8085:8080"
      - "9995:9990"
    depends_on:
      - postgres
  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
